### ISSUE TITLE
New Hex Version

### ISSUE THREAD

**Issue by asummers** [jeremyjh/dialyxir#187]
We should push a new version to hex, I think. Maybe not a 1.0 or an RC, but there hasn't been a release since January, so it's probably worthwhile to push the latest and greatest.

**Comment by jeremyjh** [comment]
I've held off on doing that since we're still getting plenty of bug reports (and fixes) just from people using master. Putting a version on Hex suggests something about stability - "put this in your mix.exs and forget about it for a few months".  Wouldn't it be better to see if things settle down for a couple of days?

**Comment by asummers** [comment]
I can buy that.

**Comment by AndrewDryga** [comment]
@jeremyjh nothing stops us from releasing rc's or beta's before it's not stable. Git dependencies are really ugly :).

**Comment by jeremyjh** [comment]
I've published 1.0.0-rc.0.
