### ISSUE TITLE
Updating PTL for dependency changes

### ISSUE THREAD

**Issue by micahrye** [jeremyjh/dialyxir#227]
I am using Dialyxir in my projects and have run into an issue with changes in local dependencies not being recognized by dialyxir when running `mix dialyzer`. 

I my project I have local dependencies that get referenced in the parent applications `mix.exs` file via `path:` 

When making changes to the dependency the dialyzer plt is never updated. 

My understanding, Erlang dialyzer, is that the command line argument [--check_plt](http://erlang.org/doc/man/dialyzer.html) should result in dialyzer checking "the PLT for consistency and rebuild it if it is not up-to-date." 

`dialyxir`  does not support the cmd line argument `--check_plt`. 

I modified my the `project/0` function of `mix.exs` and added:

```
[
...
dialyzer: [ check_plt: true ]
...
]
```
Thinking that I could pass arguments this way, but that also does not work. 

**I would like** that when I make changes to a dependency that those changes are recognized and the `plt` is updated without having to recompile the entire `plt`.

**Comment by jeremyjh** [comment]
We hash `mix.lock` and check the PLT when it changes. For local dependencies, we could add an option to force checking all the time. Its not fast, even when there are no changes. One other option would be to add the paths via `paths` key, rather than as a dependency. That would be slower too, since it would actually check the dependency as as well.

**Comment by micahrye** [comment]
Thanks @jeremyjh, is there a "convenient" way for me to update the PLT from the cmd line or other args? 

Your response seemed to be talking about potential approaches to handle the issue of local dependencies.

**Comment by micahrye** [comment]
As I have time I will hack about it some and see if I can put together anything nice. If so I will put a PR out. 

First jump in to force it to update PLT is slow, but faster than full rebuild. 

Ideally, it is not often that you need to recompile the PLT even for a single dependency, so even if it is a bit slow once that is not soooo bad, as long as it is still much faster than recompile of the entire PLT. 

Suggestions on approach appreciated. 

thx.

**Comment by jeremyjh** [comment]
The way to do this would be to add a new argument `--check-plt`, and pass that down to https://github.com/jeremyjh/dialyxir/blob/273156eecf597c641567dca0a86ff79e846a8e81/lib/mix/tasks/dialyzer.ex#L203 to skip checking the dependency_hash when it is true.

**Comment by mguimas** [comment]
@jeremyjh There is already the option `--no-check`, so the default for `mix dialyzer` should be to always to check the PLT, including when there are changes to `plt_add_apps:` in the `mix.exs` file.

In my case, I changed the `mix.exs` file in an umbrella child project like this:

```
def project do
   ...
   dialyzer: dialyzer()
   ...
end

  defp dialyzer do
    [
      plt_add_apps: [:mix],
      plt_add_deps: :app_tree
    ]
  end
```
and when running `mix dialyzer` the PLT was not updated when it should had because I modified `mix.exs` to include Mix, and its recursive deps, in the PLT (at least this was my intention with the above code, unless I did something wrong).

**Comment by jeremyjh** [comment]
@mguimas The computed apps list is included in the PLT hash, so it is checked when the computed apps list changes. Umbrella projects share dependencies, so this configuration is expected to be in the parent project.

**Comment by mguimas** [comment]
@jeremyjh I need to have `{:dialyxir, "~> 0.5", only: [:dev, :test]}` in my umbrella child project, otherwise I cannot do `mix dialyzer` inside the child. Hence it should be possible to configure on a child basis, as it makes sense only to run dialyzer only for a child project.

Likewise, we should not be forced to configure at the umbrella parent. It should be possible to configure on each child, and different childs will have different needs on what goes into the PLT.

**Comment by mguimas** [comment]
@jeremyjh I have tested this:

- I had a dependency to one of the child projects, a dependency that no other child project has. I have the entry in the umbrella parent and umbrella child projects' `mix.exs` files like this `{:dialyxir, "~> 0.5", only: [:dev, :test]}`.

- then running `mix dialyzer` inside the child project does not update the PLT, but running the same command at the parent project it updates the PLT.

The issue is that `mix dialyzer` should always try to update the PLT, whether run at the parent or child level, unless the `mix dialyzer --no-check` is run.

Does this makes sense?

**Comment by jeremyjh** [comment]
Updating the PLT always happens at the parent project level; if you launch in the child it still runs the PLT update in the parent. This doesn't really have anything to do with this current issue, which only concerns using local dependencies. Local dependencies don't work properly with the current check, because it is based on comparing a hash of the apps list and mix.lock file.

**Comment by mguimas** [comment]
I launched `mix dialyzer` in the child and it did not run the PLT update, and the dependency I added was local in that child project. The PLT check should consider local dependencies, unless `mix dialyzer --no-check` is run.

**Comment by jeremyjh** [comment]
You can open another issue for child dependencies, it has nothing to do with this issue.

**Comment by asummers** [comment]
This is now resolved on master. by adding the `--force-check` flag. Hex release will be forthcoming.
