### ISSUE TITLE
Warn on unused ignore file entry

### ISSUE THREAD

**Issue by evnu** [jeremyjh/dialyxir#277]
The feature to ignore warnings can be very useful. Would it be possible to output a warning (maybe disabled by default, configurable in `mix.exs`) if an ignore pattern did not apply anymore? That would simplify keeping the ignore file nice and clean. I think this could for example be implemented by storing the patterns in a named ETS at the beginning, and removing patterns which were used successfully.

**Comment by asummers** [comment]
I fully support a feature like this. Wanna try your hand at a PR for it? Might make sense to just pop it into the counter list that we're printing already, something like `Unnecessary skips: 3` perhaps? Or are you thinking it just prints the unnecessary warning itself?

**Comment by asummers** [comment]
@jeremyjh do we want to support a `--unused-warnings-as-errors` type flag/config in mix.exs? Where if that hypothetical counter is nonzero, we emit a nonzero exit code.

**Comment by jeremyjh** [comment]
Maybe `--unused_ignores-as-errors` ?

**Comment by evnu** [comment]
I can give a PR a try. It will take me some days, though. Is the approach with ETS reasonable, or would you prefer a different approach?

**Comment by jeremyjh** [comment]
I don't think ETS is necessary but I can see why it would be attractive.  Still, I think I'd approach it differently. First, you only need to support the `.exs` warnings.  If you have `filter_warning?` return the filter term (ignore) instead of true/false (Enum.find instead of Enum.any?), then `filter_warnings` can, instead of doing an `Enum.reject` it can `Enum.reduce` over a pair of structures: a map of used warnings, and a list of the passed warnings. 

Then you have just one more passed over the ignore file and print out any terms that aren't in the used map.

Another possibility - which would iron out another wart -  would be to start with a map of all the ignore file terms as keys and a value of 0 (since they haven't be used yet), and pass that all the way down to `filter_warning?` as its keys could be used directly instead of evaluating the file again for each warning. You still reduce over it and update the counts, and then just warn on any that were not used.

**Comment by evnu** [comment]
> Might make sense to just pop it into the counter list that we're printing already, something like Unnecessary skips: 3 perhaps? Or are you thinking it just prints the unnecessary warning itself?

I think both is a good idea. Should this be configurable (e.g. `:list_unnecessary_filters` to enable listing them)?

Example output:

```
Total errors: 1, Skipped: 1, Unnecessary Skips: 1
Unused filters:
{"a/file.ex:17:no_return Function format_long/1 has no local return."}
```
