### ISSUE TITLE
A way to ignore the typespecs of a dependency

### ISSUE THREAD

**Issue by rodrigues** [jeremyjh/dialyxir#360]
While discussing a [dialyzer issue in a hex package](https://github.com/whatyouhide/stream_data/pull/133), the author said he wants to use the typespecs more for documentation than for type checks. This happens a lot, typespecs in there more for this purpose, and as usually they're not checked, they end up breaking for dialyzer users of that dependency.

`plt_ignore_apps` won't serve as a workaround, as `unknown_function` will be the error instead.

Could we tell dialyxir/dialyzer to ignore the `@spec` of a package, dialyzing as if they weren't there?

Thanks!

**Comment by jeremyjh** [comment]
I don't think that's a common position to take, it essentially means you want to use typespecs for documentation, but you don't care if the documentation is correct.  Did you try removing this library from the PLT? You'd have to ignore some missing type warnings. You could also just ignore the warning you're getting from this typespec problem. 

Anyway, there is not really anything more I can offer in dialyxir as the dialyzer API doesn't offer us a way to ignore code you've told it to check, due to the external module it is calling into.
