### ISSUE TITLE
The --halt-exit-status overwrites other non zero status codes

### ISSUE THREAD

**Issue by RobinClowers** [jeremyjh/dialyxir#46]
the `--halt-exit-status` flag that was added in https://github.com/jeremyjh/dialyxir/issues/33 always returns the dialzyxir exit code, even if it's 0 and other tasks returned non zero codes. In our case, we have a `mix ci` task, which runs our test, dogma and dialyzer tasks. When tests fail, we get an exit code of 0.

**Comment by RobinClowers** [comment]
I see now that the help output explicitly says not to use this flag with `mix do`... So maybe this isn't bug, maybe we could include that info in the readme?

**Comment by jeremyjh** [comment]
This is definitely by design and since the option itself is not documented in readme - only in the moduledoc, where we do document this - I don't see why we particularly to mention this there. At some point I'll probably embellish and publish module docs and trim the readme so we don't have this sort of inconsistency.
