### ISSUE TITLE
Better `with` support

### ISSUE THREAD

**Issue by optikfluffel** [jeremyjh/dialyxir#48]
Given:
```elixir
defmodule PotentialBugReport do
  defp double(x), do: {:ok, 2 * x}
  defp tripple(x), do: {:ok, 3 * x}

  def foobar(x) do
    with {:ok, two_times} <- double(x),
         {:ok, three_times} <- tripple(x) do
      IO.puts "2x = #{inspect two_times} and 3x = #{inspect three_times}"
    end
  end
end
```

Dialyxir outputs:

```
potential_bug_report.ex:6: The variable _@6 can never match since previous clauses completely covered the type {'ok',number()}
potential_bug_report.ex:7: The variable _@5 can never match since previous clauses completely covered the type {'ok',number()}
```

Am I doing something wrong?

**Comment by jeremyjh** [comment]
You probably want to ask this question on one of the Elixir lists or Stackoverflow - it isn't really a question about Dialyxir (which just runs the Erlang dialyzer tool on your BEAM files) but about how the with expression gets compiled to Erlang and what the dialyzer tool makes of those forms. 

My intuition is that because your functions *must* return an {:ok, number()} that there is no alternative case for the patterns to match on, which is the whole point of the with clause (to match on some patterns that are possible results, and not others). You might try writing tripple and double such that they return {:error, "reason"} on some condition, so that there are patterns to match that are not completely overlapped by {:ok, number()}.
