### ISSUE TITLE
:dialyzer.run error: File not found: erl_bif_types.beam

### ISSUE THREAD

**Issue by apoorv-2204** [jeremyjh/dialyxir#507]
### Precheck

* Take a look at the open issues and be sure that your issue is not already covered.
* Be sure your versions of Dialyxir and Erlex are up to date.

### Environment

![image](https://github.com/jeremyjh/dialyxir/assets/90304197/fe2edafd-1071-436f-8224-51982a441599)

![image](https://github.com/jeremyjh/dialyxir/assets/90304197/ee0c8b50-3f14-4a08-aba4-9210ec785cfb)

### Current behavior
 
![image](https://github.com/jeremyjh/dialyxir/assets/90304197/37793eb2-d9ac-422c-b648-5a7abcacfcc0)

### Expected behavior
Should Compile Normally in github.

**Comment by paulo-ferraz-oliveira** [comment]
Are you using `setup-beam`? Check #506.

**Comment by apoorv-2204** [comment]
```
      - name: Setup Elixir and Erlang versions
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}



Yup

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, so between 1.15 and 1.16 we changed where elements are saved in the disk to benefit from cache speedups. Since the PLTs contain hard references to files in the filesystem it's highly likely that your cache is trying to fetch elements that aren't present any more. There's no lasting solution for this (even though we don't change cache elements that much), but a short term solution is deleting your cache and retrying.

**Comment by apoorv-2204** [comment]
# Solution 
![image](https://github.com/jeremyjh/dialyxir/assets/90304197/aee1d8f3-7ff8-467e-acc2-d8b6f5fd9e21)
This issue is Solved by cleaning the cache.
Thank you team
