### ISSUE TITLE
Wrong file paths when used in an Umbrella.

### ISSUE THREAD

**Issue by hickscorp** [jeremyjh/dialyxir#90]
I discussed this issue on the #dialyzer channel of the Elixir's Slack. I've been pointed to writting a mix task to solve this, so I'd like to get your insights first.

Problem: when running `mix dialyzer` from an umbrella project, it appears like `dialyzer` is ran in each subproject (Which is essentially fine). However, the output doesn't contain that information.

For instance, imagine an umbrella containing project `a` and `b`. If there is an issue in `apps/a/lib/a.ex`, running `mix dialyzer` will report the issue with a filename equal to `lib/a.ex`.

This is quite odd, because most tools (if not all the ones I use, eg credo, dogma, exunit) report the correct (relative to where the task was ran) `apps/a/lib/a.ex` path for when they find an issue.

Could someone please either point me on some directions to solve this, or either accept this issue?

I am attaching an example of the credo task output vs the dialyxir task output for reference.

![credo example output](https://cloud.githubusercontent.com/assets/822933/25619455/d38cb404-2f42-11e7-8d2e-718e35ff82c6.png)

![dialyxir example output](https://cloud.githubusercontent.com/assets/822933/25619471/e7e21714-2f42-11e7-9d50-f53c60b0b6f6.png)

**Comment by jeremyjh** [comment]
Credo has the benefit of operating on Elixir source files. `dialyzer` is an Erlang tool, and doesn't operate on Elixir sources so we point it at the BEAM files. The Elixir compiler includes source path information in the BEAM, so `dialyzer` is able to provide that back to us in it's warnings. Since it only includes the path information relative to the child project, that is all we get back from `dialyzer`. 

The only way I could think of to address this would be to analyze each child separately, so I know which child the errors are associated with. I'm not opposed to doing that in `dialyzer` if it doesn't hurt performance much.

**Comment by hickscorp** [comment]
@jeremyjh Thanks for investigating,

I think the proposed solution would work, and would be quite beneficial for the Elixir ecosystem, at it would allow faster integration with IDEs.

**Comment by jeremyjh** [comment]
Hi, I'm going to close this issue. Several points here:

* I don't use umbrella projects myself and in over a year no one has upvoted this issue or offered a PR.
* Running analysis in only one child at time will also cause problems because most likely your children talk to each other and reference types that will be unknown if analyzed separately
* I do not think it can be properly addressed outside the Elixir compiler, and I'm not at all sure `elixirc` can or should change anything either (including child path in the source path referenced in BEAM)
